#!/usr/bin/env node

/**
 * Copyright 2017 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// First things first, let's check dependencies
require('./lib/check-deps');

const assert = require('assert');
const fs = require('fs-extra');
const path = require('path');
const reporter = require('./lib/reporter');
const webpack = require('webpack');

const { ASSET_EXTENSIONS, BuildDir, JEKYLL_CONFIG_PATH, PROD_SITE_ROOT, } = require('./lib/project-paths');
const { JekyllConfiguration } = require('./lib/jekyll-config');
const { PlatformSite } = require('./lib/platform-site');
const { addWatchToWebpackConfig, setupFileWatches } = require('./lib/watch');
const { execSync } = require('child_process');
const { initCli } = require('./lib/cli');


// Parses and validates command line arguments.
const cli = initCli();
const platformSites = cli.input.map((repoPath) =>
    new PlatformSite(repoPath, cli.buildEnvironment == 'production' ? PROD_SITE_ROOT : ''));

// Ensure that the working directory is the project root
const projectRootPath = path.join(__dirname, '..');
process.chdir(projectRootPath);

reporter.step('Cleaning', () => {
  try {
    assert(process.cwd() == projectRootPath);
    fs.removeSync(BuildDir.STAGE);
    fs.removeSync(BuildDir.DIST);
  } catch(e) {
    console.error(e);
    process.exit(1);
  }
});

fs.copySync(BuildDir.JEKYLL, BuildDir.STAGE);

reporter.step('Processing files/directories', () => {
  platformSites.forEach((site) => {
    site.prepareForBuild(BuildDir.STAGE);
  });
});

const config = reporter.step('Preparing configuration', () => {
  const c = new JekyllConfiguration(path.join(BuildDir.STAGE, JEKYLL_CONFIG_PATH));
  platformSites.forEach((site) => c.addPlatformConfig(site.config));
  return c;
});

reporter.step('Building assets', () => {
  // TODO(shyndman): Periodically check if we can uncomment this. There's some
  // noisy deprecation deep in Webpack.
  process.noDeprecation = true;

  const webpackConfig = require('../webpack.config');
  if (cli.flags.watch) {
    addWatchToWebpackConfig(webpackConfig);
  }

  webpack(webpackConfig, (err, stats) => {
    if (err) {
      reporter.fatal(err);
      process.exit(1);
    }

    reporter.webpackStats(stats);
    buildJekyll();
  });
}, { noCheck: true });

function buildJekyll() {
  reporter.step('Building Jekyll site', () => {
    // Write out the merged config.
    config.write(path.join(BuildDir.STAGE, JEKYLL_CONFIG_PATH));

    const configPaths = [path.join(BuildDir.STAGE, '_config.yml')];
    if (cli.buildEnvironment == 'production') {
      configPaths.push(path.join(BuildDir.STAGE, '_prod-config.yml'));
    }

    const jekyllEnv = Object.assign({}, process.env, {
      BUNDLE_GEMFILE: path.join(projectRootPath, 'GEMFILE'),
    });
    execSync(`bundle exec jekyll build \
        --source ${BuildDir.STAGE} \
        --destination ${BuildDir.DIST} \
        --config ${configPaths.join(',')}`,
      {
        env: jekyllEnv,
        stdio: ['ignore', 'ignore', 'inherit'],
      });
  });

  if (!cli.flags.watch) {
    reporter.complete(path.resolve(BuildDir.DIST));
  }
}

if (cli.flags.watch) {
  setupFileWatches((filePath) => {
    reporter.fileChanged(filePath);

    const newFilePath = filePath.replace(BuildDir.JEKYLL, BuildDir.STAGE);
    fs.ensureDirSync(path.dirname(newFilePath));
    fs.copySync(filePath, newFilePath);

    const fileExt = path.extname(filePath);
    if (!ASSET_EXTENSIONS.has(fileExt)) {
      buildJekyll();
    }
  });
}
