#!/bin/bash

function shallow_clone() {
  git clone --depth 1 --shallow-submodules --branch $2 $1 
}

# Ensure cwd
cd "$(dirname "$0")/.."

echo 'Cleaning'
rm -Rf docs-src

echo 'Cloning documentation repositories'
mkdir -p docs-src
pushd docs-src

shallow_clone git@github.com:material-components/material-components-android.git master
shallow_clone git@github.com:material-components/material-components-ios.git stable
shallow_clone git@github.com:material-components/material-components-web.git master
shallow_clone git@github.com:material-components/material-components.git develop
popd

echo 'Building site'
BUILD_ENV=production scripts/build docs-src/material-components{,-android,-ios,-web}
